site_name: material-sphinx
theme:
  name: material
docs_dir: docs/sources
repo_url: https://github.com/JustinGoheen/material-sphinx
site_description: "Documentation for material-sphinx."

nav:
  - Home: index.md
  - Documentation generator: documentation_generator.md
  - Automatic gathering: automatic_gathering.md
