site_name: easy-sphinx
theme:
  name: material
docs_dir: sources
repo_url: https://github.com/JustinGoheen/easy-sphinx
site_description: "Documentation for easy-sphinx."

nav:
  - Home: index.md
  - Documentation generator: documentation_generator.md
  - Automatic gathering: automatic_gathering.md
